language: csharp
solution: test.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore test/test.sln
after_script: 
  - nunit-console test\packages\NUnit.3.9.0\lib\net45\nunit.framework.dll
