language: csharp
solution: test/test.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore test/test.sln
after_script: 
  - nunit-console test/packages/NUnit3TestAdapter.3.9.0/build/net35/NUnit3.TestAdapter.dll
