language: csharp
solution: test/test.sln
install:
  - nuget restore test/test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -test testrunner
script:
  - xbuild /p:Configuration=Debug test/test.sln
  - mono test/packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe test/bin/Release/MyProject.Tests.dll
