language: csharp
solution: test.sln
install:
  - nuget restore test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./nunittest/bin/Release/nunittest.Tests.dll
