language: csharp
solution: test/test.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore test/test.sln
after_script:
  - nunit-console test/test/bin/Debug/nunit.framework.dll
